package com.test.TestTask.exceptions;

public class UserNotFoundException extends RuntimeException{

}
